import {
  Audi_Q3,
  Audi_Q3_new,
  Audi_A4,
  Audi_A6,
  Audi_Q5,
  Bmw2series,
  Bmw5series,
  Bmwi4,
  BmwiX,
  Bmwx1,
  Bmwx3,
  Bmwx7,
  Ferrari812,
  Ferrari296,
  HondaCity,
  HondaElevate,
  Hyundaii10,
  HyundaiIoniq,
  HyundaiAura,
  HyundaiCreta,
  HyundaiExter,
  Hyundaii20,
  HyundaiKona,
  HyundaiTucson,
  HyndaiVenue,
  HyundaiVerna,
  MahindraBolero,
  MahindraScorpioN,
  MahindraXuv300,
  MahindraScorpio,
  MahindraThar,
  MahindaraXuv700,
  SuzukiAlto,
  SuzukiBaleno,
  SuzukiBrezza,
  SuzukiCelerio,
  SuzukiCiaz,
  SuzukiErtiga,
  SuzukiFronix,
  SuzukiIgnis,
  SuzukiSpresso,
  SuzukiSwift,
  SuzukiSwiftDezire,
  SuzukiWagonR,
  PorscheCayenne,
  PorsheTaycan,
  Porsche718,
  Porsche911,
  RangeRoverDefender,
  RangeRoverEvoque,
  RangeRoverVelar,
  SkodaKodiaq,
  SkodaKushaq,
  SkodaSuperb,
  SkodaSlavia,
  TataSafari,
  TataHarrier,
  TataNexon,
  VolkswagenTaigun,
  VolkswagenVirtus,
} from "../assets";

export const cars = [
  {
    "id": 1,
    "carName": "Audi Q3",
    "yearOfManufacture": 2018,
    "peopleCapacity": 5,
    "fuelType": "Gasoline",
    "range": "12 km/liter",
    "gearbox": "Automatic",
    "rateForMonthRent": 1200,
    "img": Audi_Q3
  },
  {
    "id": 2,
    "carName": "Audi Q3 2023",
    "yearOfManufacture": 2023,
    "peopleCapacity": 5,
    "fuelType": "Gasoline",
    "range": "12 km/liter",
    "gearbox": "Automatic",
    "rateForMonthRent": 1300,
    "img": Audi_Q3_new
  },
  {
    "id": 3,
    "carName": "Audi A4",
    "yearOfManufacture": 2022,
    "peopleCapacity": 5,
    "fuelType": "Gasoline",
    "range": "14 km/liter",
    "gearbox": "Automatic",
    "rateForMonthRent": 1400,
    "img": Audi_A4
  },
  {
    "id": 4,
    "carName": "Audi A6",
    "yearOfManufacture": 2022,
    "peopleCapacity": 5,
    "fuelType": "Gasoline",
    "range": "15 km/liter",
    "gearbox": "Automatic",
    "rateForMonthRent": 1500,
    "img": Audi_A6
  },
  {
    "id": 5,
    "carName": "Audi Q5",
    "yearOfManufacture": 2022,
    "peopleCapacity": 5,
    "fuelType": "Gasoline",
    "range": "14 km/liter",
    "gearbox": "Automatic",
    "rateForMonthRent": 1400,
    "img": Audi_Q5
  },
  {
    "id": 6,
    "carName": "BMW 2 Series",
    "yearOfManufacture": 2022,
    "peopleCapacity": 4,
    "fuelType": "Gasoline",
    "range": "13 km/liter",
    "gearbox": "Automatic",
    "rateForMonthRent": 1300,
    "img": Bmw2series
  },
  {
    "id": 7,
    "carName": "BMW 5 Series",
    "yearOfManufacture": 2022,
    "peopleCapacity": 5,
    "fuelType": "Gasoline",
    "range": "14 km/liter",
    "gearbox": "Automatic",
    "rateForMonthRent": 1500,
    "img": Bmw5series
  },
  {
    "id": 8,
    "carName": "BMW i4",
    "yearOfManufacture": 2023,
    "peopleCapacity": 5,
    "fuelType": "Electric",
    "range": "17 km/liter",
    "gearbox": "Automatic",
    "rateForMonthRent": 1600,
    "img": Bmwi4
  },
  {
    "id": 9,
    "carName": "BMW iX",
    "yearOfManufacture": 2023,
    "peopleCapacity": 5,
    "fuelType": "Electric",
    "range": "16 km/liter",
    "gearbox": "Automatic",
    "rateForMonthRent": 1700,
    "img": BmwiX
  },
  {
    "id": 10,
    "carName": "BMW X1",
    "yearOfManufacture": 2022,
    "peopleCapacity": 5,
    "fuelType": "Gasoline",
    "range": "13 km/liter",
    "gearbox": "Automatic",
    "rateForMonthRent": 1400,
    "img": Bmwx1
  },
  {
    "id": 11,
    "carName": "BMW X3",
    "yearOfManufacture": 2022,
    "peopleCapacity": 5,
    "fuelType": "Gasoline",
    "range": "14 km/liter",
    "gearbox": "Automatic",
    "rateForMonthRent": 1500,
    "img": Bmwx3
  },
  {
    "id": 12,
    "carName": "BMW X7",
    "yearOfManufacture": 2022,
    "peopleCapacity": 7,
    "fuelType": "Gasoline",
    "range": "13 km/liter",
    "gearbox": "Automatic",
    "rateForMonthRent": 1700,
    "img": Bmwx7
  },
  {
    "id": 13,
    "carName": "Ferrari 812",
    "yearOfManufacture": 2023,
    "peopleCapacity": 2,
    "fuelType": "Gasoline",
    "range": "8 km/liter",
    "gearbox": "Automatic",
    "rateForMonthRent": 5000,
    "img": Ferrari812
  },
  {
    "id": 14,
    "carName": "Ferrari 296",
    "yearOfManufacture": 2023,
    "peopleCapacity": 2,
    "fuelType": "Gasoline",
    "range": "7 km/liter",
    "gearbox": "Automatic",
    "rateForMonthRent": 6000,
    "img": Ferrari296
  },
  {
    "id": 15,
    "carName": "Honda City",
    "yearOfManufacture": 2022,
    "peopleCapacity": 5,
    "fuelType": "Gasoline",
    "range": "12 km/liter",
    "gearbox": "Automatic",
    "rateForMonthRent": 1100,
    "img": HondaCity
  },
  {
    "id": 16,
    "carName": "Honda Elevate",
    "yearOfManufacture": 2022,
    "peopleCapacity": 7,
    "fuelType": "Gasoline",
    "range": "14 km/liter",
    "gearbox": "Automatic",
    "rateForMonthRent": 1300,
    "img": HondaElevate
  },
  {
    "id": 17,
    "carName": "Hyundai i10",
    "yearOfManufacture": 2022,
    "peopleCapacity": 4,
    "fuelType": "Gasoline",
    "range": "11 km/liter",
    "gearbox": "Automatic",
    "rateForMonthRent": 1000,
    "img": Hyundaii10
  },
  {
    "id": 18,
    "carName": "Hyundai Ioniq",
    "yearOfManufacture": 2023,
    "peopleCapacity": 5,
    "fuelType": "Electric",
    "range": "18 km/liter",
    "gearbox": "Automatic",
    "rateForMonthRent": 1200,
    "img": HyundaiIoniq
  },
  {
    "id": 19,
    "carName": "Hyundai Aura",
    "yearOfManufacture": 2022,
    "peopleCapacity": 5,
    "fuelType": "Gasoline",
    "range": "12 km/liter",
    "gearbox": "Automatic",
    "rateForMonthRent": 1100,
    "img": HyundaiAura
  },
  {
    "id": 20,
    "carName": "Hyundai Creta",
    "yearOfManufacture": 2022,
    "peopleCapacity": 5,
    "fuelType": "Gasoline",
    "range": "12 km/liter",
    "gearbox": "Automatic",
    "rateForMonthRent": 1200,
    "img": HyundaiCreta
  },
  {
    "id": 21,
    "carName": "Hyundai Exter",
    "yearOfManufacture": 2023,
    "peopleCapacity": 5,
    "fuelType": "Electric",
    "range": "16 km/liter",
    "gearbox": "Automatic",
    "rateForMonthRent": 1400,
    "img": HyundaiExter
  },
  {
    "id": 22,
    "carName": "Hyundai i20",
    "yearOfManufacture": 2022,
    "peopleCapacity": 5,
    "fuelType": "Gasoline",
    "range": "13 km/liter",
    "gearbox": "Automatic",
    "rateForMonthRent": 1200,
    "img": Hyundaii20
  },
  {
    "id": 23,
    "carName": "Hyundai Kona",
    "yearOfManufacture": 2022,
    "peopleCapacity": 5,
    "fuelType": "Electric",
    "range": "16 km/liter",
    "gearbox": "Automatic",
    "rateForMonthRent": 1300,
    "img": HyundaiKona
  },
  {
    "id": 24,
    "carName": "Hyundai Tucson",
    "yearOfManufacture": 2022,
    "peopleCapacity": 5,
    "fuelType": "Gasoline",
    "range": "12 km/liter",
    "gearbox": "Automatic",
    "rateForMonthRent": 1400,
    "img": HyundaiTucson
  },
  {
    "id": 25,
    "carName": "Hyundai Venue",
    "yearOfManufacture": 2022,
    "peopleCapacity": 5,
    "fuelType": "Gasoline",
    "range": "13 km/liter",
    "gearbox": "Automatic",
    "rateForMonthRent": 1300,
    "img": HyndaiVenue
  },
  {
    "id": 26,
    "carName": "Hyundai Verna",
    "yearOfManufacture": 2022,
    "peopleCapacity": 5,
    "fuelType": "Gasoline",
    "range": "13 km/liter",
    "gearbox": "Automatic",
    "rateForMonthRent": 1200,
    "img": HyundaiVerna
  },
  {
    "id": 27,
    "carName": "Mahindra Bolero",
    "yearOfManufacture": 2022,
    "peopleCapacity": 7,
    "fuelType": "Diesel",
    "range": "15 km/liter",
    "gearbox": "Manual",
    "rateForMonthRent": 1100,
    "img": MahindraBolero
  },
  {
    "id": 28,
    "carName": "Mahindra Scorpio",
    "yearOfManufacture": 2022,
    "peopleCapacity": 7,
    "fuelType": "Diesel",
    "range": "14 km/liter",
    "gearbox": "Manual",
    "rateForMonthRent": 1200,
    "img": MahindraScorpio
  },
  {
    "id": 29,
    "carName": "Mahindra Scorpio New",
    "yearOfManufacture": 2023,
    "peopleCapacity": 7,
    "fuelType": "Diesel",
    "range": "14 km/liter",
    "gearbox": "Manual",
    "rateForMonthRent": 1300,
    "img": MahindraScorpioN
  },
  {
    "id": 30,
    "carName": "Mahindra XUV300",
    "yearOfManufacture": 2022,
    "peopleCapacity": 5,
    "fuelType": "Diesel",
    "range": "15 km/liter",
    "gearbox": "Manual",
    "rateForMonthRent": 1200,
    "img": MahindraXuv300
  },
  {
    "id": 31,
    "carName": "Mahindra Thar",
    "yearOfManufacture": 2022,
    "peopleCapacity": 4,
    "fuelType": "Diesel",
    "range": "14 km/liter",
    "gearbox": "Manual",
    "rateForMonthRent": 1300,
    "img": MahindraThar
  },
  {
    "id": 32,
    "carName": "Mahindra XUV700",
    "yearOfManufacture": 2022,
    "peopleCapacity": 7,
    "fuelType": "Diesel",
    "range": "13 km/liter",
    "gearbox": "Automatic",
    "rateForMonthRent": 1500,
    "img": MahindaraXuv700
  },
  {
    "id": 33,
    "carName": "Maruti Suzuki Alto",
    "yearOfManufacture": 2022,
    "peopleCapacity": 4,
    "fuelType": "Gasoline",
    "range": "15 km/liter",
    "gearbox": "Manual",
    "rateForMonthRent": 900,
    "img": SuzukiAlto
  },
  {
    "id": 34,
    "carName": "Maruti Suzuki Baleno",
    "yearOfManufacture": 2022,
    "peopleCapacity": 5,
    "fuelType": "Gasoline",
    "range": "14 km/liter",
    "gearbox": "Automatic",
    "rateForMonthRent": 1100,
    "img": SuzukiBaleno
  },
  {
    "id": 35,
    "carName": "Maruti Suzuki Brezza",
    "yearOfManufacture": 2022,
    "peopleCapacity": 5,
    "fuelType": "Gasoline",
    "range": "13 km/liter",
    "gearbox": "Automatic",
    "rateForMonthRent": 1000,
    "img": SuzukiBrezza
  },
  {
    "id": 36,
    "carName": "Maruti Suzuki Ciaz",
    "yearOfManufacture": 2022,
    "peopleCapacity": 5,
    "fuelType": "Gasoline",
    "range": "14 km/liter",
    "gearbox": "Automatic",
    "rateForMonthRent": 1100,
    "img": SuzukiCiaz
  },
  {
    "id": 37,
    "carName": "Maruti Suzuki Ertiga",
    "yearOfManufacture": 2022,
    "peopleCapacity": 7,
    "fuelType": "Gasoline",
    "range": "12 km/liter",
    "gearbox": "Automatic",
    "rateForMonthRent": 1300,
    "img": SuzukiErtiga
  },
  {
    "id": 38,
    "carName": "Maruti Suzuki Swift",
    "yearOfManufacture": 2022,
    "peopleCapacity": 5,
    "fuelType": "Gasoline",
    "range": "14 km/liter",
    "gearbox": "Automatic",
    "rateForMonthRent": 1000,
    "img": SuzukiSwift
  },
  {
    "id": 39,
    "carName": "Maruti Suzuki Wagon R",
    "yearOfManufacture": 2022,
    "peopleCapacity": 5,
    "fuelType": "Gasoline",
    "range": "13 km/liter",
    "gearbox": "Automatic",
    "rateForMonthRent": 900,
    "img": SuzukiWagonR
  },
  {
    "id": 40,
    "carName": "Maruti Suzuki Celerio",
    "yearOfManufacture": 2022,
    "peopleCapacity": 5,
    "fuelType": "Gasoline",
    "range": "13 km/liter",
    "gearbox": "Automatic",
    "rateForMonthRent": 1600,
    "img": SuzukiCelerio
  },
  {
    "id": 41,
    "carName": "Maruti Suzuki Fronix",
    "yearOfManufacture": 2022,
    "peopleCapacity": 5,
    "fuelType": "Gasoline",
    "range": "14 km/liter",
    "gearbox": "Automatic",
    "rateForMonthRent": 1700,
    "img": SuzukiFronix
  },
  {
    "id": 42,
    "carName": "Maruti Suzuki Ignis",
    "yearOfManufacture": 2023,
    "peopleCapacity": 5,
    "fuelType": "Electric",
    "range": "16 km/liter",
    "gearbox": "Automatic",
    "rateForMonthRent": 1800,
    "img": SuzukiIgnis
  },
  {
    "id": 43,
    "carName": "Maruti Suzuki Spresso",
    "yearOfManufacture": 2022,
    "peopleCapacity": 5,
    "fuelType": "Gasoline",
    "range": "13 km/liter",
    "gearbox": "Automatic",
    "rateForMonthRent": 1800,
    "img": SuzukiSpresso
  },
  {
    "id": 44,
    "carName": "Maruti Suzuki Dezire",
    "yearOfManufacture": 2022,
    "peopleCapacity": 7,
    "fuelType": "Gasoline",
    "range": "12 km/liter",
    "gearbox": "Automatic",
    "rateForMonthRent": 2000,
    "img": SuzukiSwiftDezire
  },
  {
    "id": 45,
    "carName": "Porsche Cayenne",
    "yearOfManufacture": 2022,
    "peopleCapacity": 5,
    "fuelType": "Gasoline",
    "range": "12 km/liter",
    "gearbox": "Automatic",
    "rateForMonthRent": 1000,
    "img": PorscheCayenne
  },
  {
    "id": 46,
    "carName": "Porsche Taycan",
    "yearOfManufacture": 2022,
    "peopleCapacity": 5,
    "fuelType": "Gasoline",
    "range": "13 km/liter",
    "gearbox": "Automatic",
    "rateForMonthRent": 1100,
    "img": PorsheTaycan
  },
  {
    "id": 47,
    "carName": "Porsche 718",
    "yearOfManufacture": 2022,
    "peopleCapacity": 2,
    "fuelType": "Gasoline",
    "range": "7 km/liter",
    "gearbox": "Automatic",
    "rateForMonthRent": 5000,
    "img": Porsche718
  },
  {
    "id": 48,
    "carName": "Porsche 911",
    "yearOfManufacture": 2022,
    "peopleCapacity": 5,
    "fuelType": "Electric",
    "range": "16 km/liter",
    "gearbox": "Automatic",
    "rateForMonthRent": 6200,
    "img": Porsche911
  },
  {
    "id": 49,
    "carName": "Range Rover Evoque",
    "yearOfManufacture": 2022,
    "peopleCapacity": 7,
    "fuelType": "Gasoline",
    "range": "10 km/liter",
    "gearbox": "Automatic",
    "rateForMonthRent": 2200,
    "img": RangeRoverEvoque
  },
  {
    "id": 50,
    "carName": "Range Rover Velar",
    "yearOfManufacture": 2022,
    "peopleCapacity": 5,
    "fuelType": "Gasoline",
    "range": "11 km/liter",
    "gearbox": "Automatic",
    "rateForMonthRent": 3000,
    "img": RangeRoverVelar
  },
  {
    "id": 51,
    "carName": "Range Rover Defender",
    "yearOfManufacture": 2023,
    "peopleCapacity": 5,
    "fuelType": "Diesel",
    "range": "11 km/liter",
    "gearbox": "Automatic",
    "rateForMonthRent": 1900,
    "img": RangeRoverDefender
  },
  {
    "id": 52,
    "carName": "Skoda Kodiaq",
    "yearOfManufacture": 2023,
    "peopleCapacity": 7,
    "fuelType": "Gasoline",
    "range": "11 km/liter",
    "gearbox": "Automatic",
    "rateForMonthRent": 1400,
    "img": SkodaKodiaq
  },
  {
    "id": 53,
    "carName": "Skoda Kushaq",
    "yearOfManufacture": 2023,
    "peopleCapacity": 5,
    "fuelType": "Gasoline",
    "range": "13 km/liter",
    "gearbox": "Automatic",
    "rateForMonthRent": 1200,
    "img": SkodaKushaq
  },
  {
    "id": 54,
    "carName": "Skoda Superb",
    "yearOfManufacture": 2023,
    "peopleCapacity": 5,
    "fuelType": "Gasoline",
    "range": "14 km/liter",
    "gearbox": "Automatic",
    "rateForMonthRent": 1500,
    "img": SkodaSuperb
  },
  {
    "id": 55,
    "carName": "Skoda Slavia",
    "yearOfManufacture": 2023,
    "peopleCapacity": 5,
    "fuelType": "Gasoline",
    "range": "13 km/liter",
    "gearbox": "Automatic",
    "rateForMonthRent": 1300,
    "img": SkodaSlavia
  },
  {
    "id": 56,
    "carName": "Tata Safari",
    "yearOfManufacture": 2022,
    "peopleCapacity": 7,
    "fuelType": "Diesel",
    "range": "11 km/liter",
    "gearbox": "Automatic",
    "rateForMonthRent": 1200,
    "img": TataSafari
  },
  {
    "id": 57,
    "carName": "Tata Harrier",
    "yearOfManufacture": 2022,
    "peopleCapacity": 5,
    "fuelType": "Diesel",
    "range": "12 km/liter",
    "gearbox": "Automatic",
    "rateForMonthRent": 1100,
    "img": TataHarrier
  },
  {
    "id": 58,
    "carName": "Tata Nexon",
    "yearOfManufacture": 2022,
    "peopleCapacity": 5,
    "fuelType": "Diesel",
    "range": "12 km/liter",
    "gearbox": "Automatic",
    "rateForMonthRent": 1100,
    "img": TataNexon
  },
  {
    "id": 59,
    "carName": "Volkswagen Taigun",
    "yearOfManufacture": 2022,
    "peopleCapacity": 5,
    "fuelType": "Gasoline",
    "range": "12 km/liter",
    "gearbox": "Automatic",
    "rateForMonthRent": 1200,
    "img": VolkswagenTaigun
  },
  {
    "id": 60,
    "carName": "Volkswagen Virtus",
    "yearOfManufacture": 2022,
    "peopleCapacity": 5,
    "fuelType": "Gasoline",
    "range": "12 km/liter",
    "gearbox": "Automatic",
    "rateForMonthRent": 1200,
    "img": VolkswagenVirtus
  }
]

