export const searchRecomendation = [
  "Audi",
  "BMW",
  "Ferrari",
  "Hyundai",
  "Honda",
  "Maruti Suzuki",
  "Mahindra",
  "Porsche",
  "Range Rover",
  "Skoda",
  "Tata",
  "Volkswagen",
  "Audi Q3",
  "Audi Q3 2023",
  "Audi A4",
  "Audi A6",
  "Audi Q5",
  "BMW 2 Series",
  "BMW 5 Series",
  "BMW i4",
  "BMW iX",
  "BMW X1",
  "BMW X3",
  "BMW X7",
  "Ferrari 812",
  "Ferrari 296",
  "Honda City",
  "Honda Elevate",
  "Hyundai i10",
  "Hyundai Ioniq",
  "Hyundai Aura",
  "Hyundai Creta",
  "Hyundai Exter",
  "Hyundai i20",
  "Hyundai Kona",
  "Hyundai Tucson",
  "Hyundai Venue",
  "Hyundai Verna",
  "Mahindra Bolero",
  "Mahindra Scorpio",
  "Mahindra Scorpio New",
  "Mahindra XUV300",
  "Mahindra Thar",
  "Mahindra XUV700",
  "Maruti Suzuki Alto",
  "Maruti Suzuki Baleno",
  "Maruti Suzuki Brezza",
  "Maruti Suzuki Ciaz",
  "Maruti Suzuki Ertiga",
  "Maruti Suzuki Swift",
  "Maruti Suzuki Wagon R",
  "Maruti Suzuki Celerio",
  "Maruti Suzuki Fronix",
  "Maruti Suzuki Ignis",
  "Maruti Suzuki Spresso",
  "Maruti Suzuki Dezire",
  "Porsche Cayenne",
  "Porsche Taycan",
  "Porsche 718",
  "Porsche 911",
  "Range Rover Evoque",
  "Range Rover Velar",
  "Range Rover Defender",
  "Skoda Kodiaq",
  "Skoda Kushaq",
  "Skoda Superb",
  "Skoda Slavia",
  "Tata Safari",
  "Tata Harrier",
  "Tata Nexon",
  "Volkswagen Taigun",
  "Volkswagen Virtus",
];
